import java.util.*;

public class Solution {
    public static void main(String[] args) {
        Subject subject = new Subject("Технологии программирования", "Самойлов Виктор Геннадьевич");
        Student st1 = new Student("Дарья", "Белоусова");
        Student st2 = new Student("Жанна", "Борушевская");
        Student st3 = new Student("Дамир", "Гильманов");
        Student st4 = new Student("Асель", "Казеева");
        ArrayList<Student> Students = new ArrayList<Student>();
        Students.add(st1);
        Students.add(st2);
        Students.add(st3);
        Students.add(st4);
        Group gr411 = new Group("CSIT", "411", Students);
        Date date = new Date(2016, 1, 18);
        Date date1 = new Date(2016, 1, 25);
        Date date2 = new Date(2016, 2, 1);
        Date date3 = new Date(2016, 2, 8);
        Date date4 = new Date(2016, 2, 15);
        ArrayList<Date> dats = new ArrayList<>();
        dats.add(date);
        dats.add(date1);
        dats.add(date2);
        dats.add(date3);
        dats.add(date4);
        ArrayList<Integer> pos = new ArrayList<>();
        pos.add(1);
        pos.add(1);
        pos.add(1);
        pos.add(1);
        ArrayList<Integer> pos1 = new ArrayList<>();
        pos1.add(1);
        pos1.add(0);
        pos1.add(1);
        pos1.add(1);
        ArrayList<Integer> pos2 = new ArrayList<>();
        pos2.add(1);
        pos2.add(1);
        pos2.add(0);
        pos2.add(0);
        ArrayList<Integer> pos3 = new ArrayList<>();
        pos3.add(1);
        pos3.add(0);
        pos3.add(1);
        pos3.add(1);
        ArrayList<Integer> pos4 = new ArrayList<>();
        pos4.add(0);
        pos4.add(0);
        pos4.add(0);
        pos4.add(1);
        ArrayList<ArrayList<Integer>> posech = new ArrayList<>();
        posech.add(pos);
        posech.add(pos1);
        posech.add(pos2);
        posech.add(pos3);
        posech.add(pos4);
        Attendance posx = new Attendance(gr411, subject, dats, posech);
        posx.printGroupPos();
        System.out.println("\n\n");
        System.out.println("Был-ли " + st3.LastName + " " + st3.FirstName + " на паре " + date3 + "?");
        System.out.println(posx.existsStudent(st3, date3));
        System.out.println("\n\n");
        System.out.println("Количество пропусков за семестр у студента: " + st3.LastName + " " + st3.FirstName);
        System.out.println(posx.skipCountStud(st3));
        System.out.println("\n\n");
        posx.printGroupSkip();
    }
}
